-- ── 026_studio_personas.sql ──────────────────────────────────────────────────
-- Avatar Studio, part 1 of 4: identity.
--
-- An `avatar` is a persona that posts. Three modes:
--   synthetic  — invented face, no real person depicted. No consent needed.
--   twin       — a real person who filmed themselves. Consent REQUIRED.
--   reference  — likeness built from supplied photographs. Consent REQUIRED.
-- Modes twin/reference must carry a verified row in consent_records before any
-- generation is permitted. Enforced in the service layer; the FK makes it visible.
--
-- tenant_id NULL on catalogue_faces / expression_presets / prompt_vocabulary
-- means "platform-level, shared by every tenant" — the same convention
-- 025_agent_definitions.sql uses for template definitions.

-- 1. Consent records ----------------------------------------------------------
-- Written BEFORE an avatar in modes twin/reference. Also the audit artefact the
-- IT Rules 2026 amendment expects an AI tool to be able to produce on demand.
CREATE TABLE IF NOT EXISTS consent_records (
  id                  SERIAL PRIMARY KEY,
  tenant_id           INTEGER     NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  subject_name        TEXT        NOT NULL,
  method              TEXT        NOT NULL DEFAULT 'hosted_capture',  -- hosted_capture | prerecorded | indemnity
  statement_language  TEXT,                                           -- consent may be spoken in any language
  video_url           TEXT,
  reference_asset_url TEXT,                                           -- what the consent video was matched against
  verified            BOOLEAN     NOT NULL DEFAULT FALSE,
  verified_at         TIMESTAMPTZ,
  verified_by         INTEGER     REFERENCES users(id) ON DELETE SET NULL,
  match_score         NUMERIC(6,4),                                   -- similarity vs reference material
  notes               TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_consent_records_tenant ON consent_records(tenant_id);

-- 2. Catalogue faces ----------------------------------------------------------
-- The browsable pool. Every face here is generated by us and depicts nobody.
-- A tenant browses, picks a direction, gets variations, and CLAIMS one — at
-- which point the row is retired from the pool and bound to their avatar.
CREATE TABLE IF NOT EXISTS catalogue_faces (
  id                SERIAL PRIMARY KEY,
  slug              TEXT        NOT NULL UNIQUE,
  facets            JSONB       NOT NULL DEFAULT '{}'::jsonb,  -- {age_band, region, face_shape, hair, build, skin_tone, register}
  base_checkpoint   TEXT        NOT NULL,
  preview_url       TEXT,
  lora_path         TEXT,                                       -- pre-trained: free tier generates against this
  parent_face_id    INTEGER     REFERENCES catalogue_faces(id) ON DELETE SET NULL, -- variation lineage
  status            TEXT        NOT NULL DEFAULT 'available',   -- available | claimed | retired
  claimed_tenant_id INTEGER     REFERENCES tenants(id) ON DELETE SET NULL,
  claimed_at        TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogue_faces_status ON catalogue_faces(status);
CREATE INDEX IF NOT EXISTS idx_catalogue_faces_facets ON catalogue_faces USING GIN (facets);

-- 3. Avatars ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS avatars (
  id                 SERIAL PRIMARY KEY,
  tenant_id          INTEGER     NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  slug               TEXT        NOT NULL,
  name               TEXT        NOT NULL,
  mode               TEXT        NOT NULL DEFAULT 'synthetic',   -- synthetic | twin | reference
  status             TEXT        NOT NULL DEFAULT 'draft',       -- draft | active | retired
  catalogue_face_id  INTEGER     REFERENCES catalogue_faces(id) ON DELETE SET NULL,
  consent_record_id  INTEGER     REFERENCES consent_records(id) ON DELETE RESTRICT,

  -- The persona bible. `bible` is the whole document; the two columns below are
  -- lifted out because they are concatenated verbatim into every prompt and must
  -- never be paraphrased by a model.
  bible              JSONB       NOT NULL DEFAULT '{}'::jsonb,
  identity_block     TEXT        NOT NULL DEFAULT '',
  avoid_block        TEXT        NOT NULL DEFAULT '',
  lora_trigger       TEXT,
  bible_version      INTEGER     NOT NULL DEFAULT 1,

  -- Voice, locked like the face.
  voice_provider     TEXT,                                       -- elevenlabs | fishaudio | openai
  voice_id           TEXT,
  voice_locked_at    TIMESTAMPTZ,

  disclosure_line    TEXT        NOT NULL DEFAULT 'AI-generated virtual creator',
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (tenant_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_avatars_tenant ON avatars(tenant_id);

-- 4. LoRAs, versioned ---------------------------------------------------------
-- Retrain on any change to identity_block. Old posts stay explainable because
-- assets record which lora_id produced them.
CREATE TABLE IF NOT EXISTS avatar_loras (
  id                  SERIAL PRIMARY KEY,
  avatar_id           INTEGER     NOT NULL REFERENCES avatars(id) ON DELETE CASCADE,
  version             INTEGER     NOT NULL,
  file_path           TEXT        NOT NULL,
  trigger_token       TEXT        NOT NULL,
  base_checkpoint     TEXT        NOT NULL,
  seed_set_ref        TEXT,                                       -- storage prefix of the training images
  seed_set_count      INTEGER,
  -- Mean face embedding of the seed set. JSONB array of floats keeps this
  -- portable; move to pgvector when similarity search (rather than comparison)
  -- is needed.
  face_embedding_mean JSONB,
  network_rank        INTEGER     DEFAULT 32,
  network_alpha       INTEGER     DEFAULT 16,
  epochs              INTEGER     DEFAULT 12,
  train_resolution    INTEGER     DEFAULT 768,
  trained_at          TIMESTAMPTZ,
  training_cost_cents INTEGER     DEFAULT 0,
  active              BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (avatar_id, version)
);

CREATE INDEX IF NOT EXISTS idx_avatar_loras_avatar ON avatar_loras(avatar_id);
-- At most one active LoRA per avatar.
CREATE UNIQUE INDEX IF NOT EXISTS uq_avatar_loras_active
  ON avatar_loras(avatar_id) WHERE active;

-- 5. Look profile — frozen at setup -------------------------------------------
-- One row per avatar. These are the choices the creator never sees again after
-- the wizard; they are appended to every generation.
CREATE TABLE IF NOT EXISTS look_profiles (
  avatar_id          INTEGER     PRIMARY KEY REFERENCES avatars(id) ON DELETE CASCADE,
  base_look          TEXT        NOT NULL DEFAULT 'editorial',    -- editorial | warm_film | clean_digital | grainy_street
  lens               TEXT        NOT NULL DEFAULT 'portrait_85',  -- portrait_85 | natural_50 | environmental_35
  colour             TEXT        NOT NULL DEFAULT 'warm',         -- warm | neutral | cool | contrast
  grain              TEXT        NOT NULL DEFAULT 'fine',         -- none | fine | visible
  skin               TEXT        NOT NULL DEFAULT 'natural',      -- subtle | natural | textured
  natural_asymmetry  BOOLEAN     NOT NULL DEFAULT TRUE,
  hair_detail        BOOLEAN     NOT NULL DEFAULT TRUE,
  vocabulary_version INTEGER     NOT NULL DEFAULT 1,
  locked_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Expression presets -------------------------------------------------------
-- A button is a stored recipe, never a model. tenant_id NULL = platform preset.
-- `blend_with` covers the cases that are not one of the base emotions:
--   weird  = contempt + confused, low intensity
--   crying = sad at high intensity + a follow-on inpaint pass for tears
CREATE TABLE IF NOT EXISTS expression_presets (
  id                SERIAL PRIMARY KEY,
  tenant_id         INTEGER     REFERENCES tenants(id) ON DELETE CASCADE,
  key               TEXT        NOT NULL,
  label             TEXT        NOT NULL,
  base_emotion      TEXT        NOT NULL,                        -- one of the twelve
  blend_with        TEXT,
  blend_ratio       NUMERIC(4,3),
  default_intensity TEXT        NOT NULL DEFAULT 'medium',       -- light | medium | strong
  follow_on_pass    TEXT,                                        -- e.g. 'tears_inpaint'
  sort_order        INTEGER     NOT NULL DEFAULT 100,
  enabled           BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (tenant_id, key)
);
-- Platform presets have tenant_id NULL, which the UNIQUE above cannot police.
CREATE UNIQUE INDEX IF NOT EXISTS uq_expression_presets_platform_key
  ON expression_presets(key) WHERE tenant_id IS NULL;

-- 7. Expression baselines — the QC calibration --------------------------------
-- A crying face legitimately scores lower than a neutral one. Calibrate once per
-- (avatar, lora, preset) at setup; the gate then measures deviation from THIS
-- value, not from neutral. Without this the gate silently eats every emotional
-- shot and you conclude the model "can't do crying".
CREATE TABLE IF NOT EXISTS expression_baselines (
  id                  SERIAL PRIMARY KEY,
  avatar_id           INTEGER     NOT NULL REFERENCES avatars(id) ON DELETE CASCADE,
  lora_id             INTEGER     NOT NULL REFERENCES avatar_loras(id) ON DELETE CASCADE,
  preset_key          TEXT        NOT NULL,
  framing             TEXT        NOT NULL DEFAULT 'medium',     -- a wide shot has less face to measure
  expected_similarity NUMERIC(6,4) NOT NULL,
  tolerance           NUMERIC(6,4) NOT NULL DEFAULT 0.0500,
  sample_count        INTEGER     NOT NULL DEFAULT 0,
  calibrated_at       TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (avatar_id, lora_id, preset_key, framing)
);

-- 8. Prompt vocabulary — versioned option → fragment --------------------------
-- The creator picks an option; the system owns the string. Improving a fragment
-- here improves every tenant's output with no action from them.
--
-- The subtractive half of the design is enforced by ABSENCE: there is no row
-- anywhere emitting "flawless skin" or "porcelain complexion", so no combination
-- of choices can produce them.
CREATE TABLE IF NOT EXISTS prompt_vocabulary (
  id          SERIAL PRIMARY KEY,
  version     INTEGER     NOT NULL DEFAULT 1,
  facet       TEXT        NOT NULL,                              -- base_look | lens | colour | grain | skin | light_direction | ...
  option_key  TEXT        NOT NULL,
  fragment    TEXT        NOT NULL,
  avoid_terms TEXT,                                              -- used only by models that honour a negative prompt
  sort_order  INTEGER     NOT NULL DEFAULT 100,
  active      BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (version, facet, option_key)
);

CREATE INDEX IF NOT EXISTS idx_prompt_vocabulary_lookup
  ON prompt_vocabulary(version, facet, option_key) WHERE active;
